# Register a per-user Scheduled Task that runs `git-ai bg start` when the user
# logs on, so the Git AI background service is up before the first git command.
#
# Usage (run as the user, NOT elevated):
#   install-login-start.ps1 [install] [--env KEY=VALUE]... [--bin PATH] [--no-start]
#   install-login-start.ps1 --uninstall
#
# Piped installs (`irm ... | iex`) get the defaults; download the file to pass flags.
#
# The task only *starts* the daemon. It never supervises it: the daemon
# restarts and updates itself, and a second instance exits because the daemon
# lock is held. See mdm/README.md for the invariants this file must keep.

$ErrorActionPreference = 'Stop'

$TaskPath = '\GitAI\'
$TaskName = 'Start bg at logon'
$LauncherDir = Join-Path $HOME '.git-ai\login'
$LauncherPath = Join-Path $LauncherDir 'start-bg.ps1'
$DefaultBin = Join-Path $HOME '.git-ai\bin\git-ai.exe'

$Mode = 'install'
$Start = $true
$Bin = ''
$EnvPairs = @()

function Fail([string]$Message) {
    [Console]::Error.WriteLine("git-ai login-start: $Message")
    exit 1
}

function Show-Usage {
    @'
Usage:
  install-login-start.ps1 [install] [--env KEY=VALUE]... [--bin PATH] [--no-start]
  install-login-start.ps1 --uninstall

Registers a per-user Scheduled Task (\GitAI\Start bg at logon) that runs
`git-ai bg start` at logon. Run as the user, not from an elevated shell.
'@
}

# $args is $null when the script body is piped through iex.
$remaining = @($args | Where-Object { $null -ne $_ })
while ($remaining.Count -gt 0) {
    $arg = $remaining[0]
    $remaining = @($remaining | Select-Object -Skip 1)
    switch -Regex ($arg) {
        '^install$' { }
        '^(--uninstall|-Uninstall)$' { $Mode = 'uninstall' }
        '^(--no-start|-NoStart)$' { $Start = $false }
        '^(--bin|-Bin)$' {
            if ($remaining.Count -eq 0) { Fail '--bin requires a path' }
            $Bin = $remaining[0]
            $remaining = @($remaining | Select-Object -Skip 1)
        }
        '^--bin=' { $Bin = $arg.Substring(6) }
        '^(--env|-Env)$' {
            if ($remaining.Count -eq 0) { Fail '--env requires KEY=VALUE' }
            $EnvPairs += $remaining[0]
            $remaining = @($remaining | Select-Object -Skip 1)
        }
        '^--env=' { $EnvPairs += $arg.Substring(6) }
        '^(-h|--help|-Help)$' { Show-Usage; exit 0 }
        default { Show-Usage | Write-Host; Fail "unknown argument: $arg" }
    }
}

foreach ($pair in $EnvPairs) {
    if ($pair -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') {
        Fail "--env expects KEY=VALUE, got '$pair'"
    }
}

if ($Mode -eq 'uninstall') {
    Unregister-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Remove-Item -LiteralPath $LauncherPath -Force -ErrorAction SilentlyContinue
    Write-Host "git-ai login-start: removed task $TaskPath$TaskName"
    exit 0
}

$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principalObj = New-Object Security.Principal.WindowsPrincipal($identity)
if ($principalObj.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning 'git-ai login-start: running elevated. The task is registered for this user only; run as the target user from a non-elevated shell for MDM rollouts.'
}

if (-not $Bin) { $Bin = $DefaultBin }
if (-not (Test-Path -LiteralPath $Bin -PathType Leaf)) {
    Fail "$Bin not found; install git-ai first or pass --bin"
}
$Bin = (Resolve-Path -LiteralPath $Bin).Path

function ConvertTo-Literal([string]$Value) {
    return "'" + $Value.Replace("'", "''") + "'"
}

# Scheduled Tasks have no environment field, so a tiny launcher sets any
# requested variables and then hands off to `bg start`.
$launcherLines = @('# Generated by git-ai install-login-start.ps1; re-run that script to change.')
foreach ($pair in $EnvPairs) {
    $key, $value = $pair.Split('=', 2)
    $launcherLines += "`$env:$key = $(ConvertTo-Literal $value)"
}
# --retry-secs rides out a daemon that is still releasing its lock at logon
# (fast logoff/logon, self-update in progress).
$launcherLines += "& $(ConvertTo-Literal $Bin) bg start --retry-secs 10"
$launcherLines += 'exit $LASTEXITCODE'

New-Item -ItemType Directory -Path $LauncherDir -Force | Out-Null
Set-Content -LiteralPath $LauncherPath -Value ($launcherLines -join "`r`n") -Encoding UTF8

$userId = "$env:USERDOMAIN\$env:USERNAME"
$action = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$LauncherPath`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -User $userId
# Interactive + Limited: runs inside the user's own logon session, unelevated,
# which is what the per-user daemon lock and named pipes require.
$principal = New-ScheduledTaskPrincipal -UserId $userId -LogonType Interactive -RunLevel Limited
# IgnoreNew: a second logon trigger must not race the running daemon.
# ExecutionTimeLimit 0 (PT0S) disables the limit so Task Scheduler never ends
# the instance and tears down the processes it started.
$settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

Register-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null

if ($Start) {
    Start-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName
}

Write-Host "git-ai login-start: installed task $TaskPath$TaskName (launcher: $LauncherPath)"
